
#' Simulated Annealing call simulations function
#'
#' @description Simulated Annealing call simulations function
#'
#' @param nl nl object
#' @param seed current model seed
#' @param cleanup indicate which filetypes should be deleted
#' @aliases util_run_nl_dyn_GenSA
#' @rdname util_run_nl_dyn_GenSA
#' @keywords internal
util_run_nl_dyn_GenSA <- function(nl, seed, cleanup) {

  # Get GenSA object from simdesign:
  gensa <- getsim(nl, "simobject")

  # Call the GenSA function from the GenSA package:
  results <- GenSA::GenSA(par = NULL,
                          fn = function(par, ...) {
                            util_run_nl_dyn_GenSA_fn(param = par,
                                                     nl = nl,
                                                     evalcrit = gensa$evalcrit,
                                                     seed = seed,
                                                     cleanup = cleanup,
                                                     ...)},
                          control=gensa$control,
                          lower=as.vector(gensa$lower),
                          upper=as.vector(gensa$upper))

  return(results)

}


#' Simulated Annealing run simulation function
#'
#' @description Simulated Annealing run simulation function
#'
#' @param param vector of model parameters, generated by GenSA function
#' @param nl nl object
#' @param evalcrit evaluation criterion for simulated annealing
#' @param seed current model seed
#' @param cleanup indicate which filetypes should be deleted
#' @aliases util_run_nl_dyn_GenSA_fn
#' @rdname util_run_nl_dyn_GenSA_fn
#' @keywords internal
util_run_nl_dyn_GenSA_fn <- function(param, nl, evalcrit, seed, cleanup) {

  # Generate a parameterset:
  names(param) <- names(getexp(nl, "variables"))

  gensa_param <- tibble::as.tibble(cbind(as.tibble(t(param)),
                                         getexp(nl, "constants"),
                                         stringsAsFactors=FALSE))

  # Attach current parameterisation to nl object:
  setsim(nl, "siminput") <- gensa_param
  # Call netlogo:
  results <- run_nl(nl = nl,
                    siminputrow = 1,
                    seed = seed)

  # Select metric for gensa:
  results <- results[evalcrit]
  # Calc mean and convert to numeric:
  if (nrow(results) > 1) {
    results <- mean(results)
  }
  results <- as.numeric(results)

  return(results)

}

